# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [1]:
import numpy as np
import sys

## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [12]:
python_array = [0] * 1000
print(sys.getsizeof(python_array))

8056


In [13]:
numpy_array = np.zeros(1000, dtype=np.int8)
print(numpy_array.nbytes)

1000


## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [14]:
array = np.array([1.0, 2.5, 3.5, 4.0, 5.5])
first, third, last = array[[0, 2, -1]]
print(f"First: {first}, Third: {third}, Last: {last}")

First: 1.0, Third: 3.5, Last: 5.5


## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [31]:
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])
print(array[[0, 1, 4, -1]])
print(array[[0, 1, 4, -1]].sum())

[ 2.3  7.8  5.8 11.1]
27.0


## Task 5

You have a matrix `A`:

```python
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])
```

Follow the comments in the next cells and write the code.

In [28]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [29]:
A.mean(axis=0)

array([2. , 8.4])

### Task 5.2 Get the standard deviation by `y` axis

In [32]:
A.std(axis=1)

array([2.5, 3. , 4. , 3.5, 3. ])

### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [33]:
A.sum(axis=1)

array([ 7, 10, 14, 13,  8])

### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [34]:
A[[0, 1]]

array([[1, 6],
       [2, 8]])

##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [35]:
A[[0, 2, -1]]

array([[ 1,  6],
       [ 3, 11],
       [ 1,  7]])

## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [41]:
[i for i in range(1000000)]

60.7 ms ± 1.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [55]:
%timeit np.arange(1000000)

2.21 ms ± 221 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### Task 6.2

In [11]:
# Python code
def unknown_signature(vector1, vector2):
    result = 0
    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]
    return result

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]


%timeit unknown_signature(vector1, vector2)
unknown_signature(vector1, vector2)

330 ns ± 17.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


32

In [12]:
%timeit np.dot(vector1, vector2)
np.dot(vector1, vector2)

2.53 μs ± 301 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


np.int64(32)

### Task 6.3

In [13]:
# Python code
def unknown_signature(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

%timeit unknown_signature(matrix1, matrix2)
unknown_signature(matrix1, matrix2)

892 ns ± 44.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


[[5, 12], [21, 32]]

In [14]:
%timeit np.multiply(matrix1, matrix2)
np.multiply(matrix1, matrix2)

2.88 μs ± 135 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


array([[ 5, 12],
       [21, 32]])

### Task 6.4

In [59]:
# Python code
def unknown_signature(lst):
    total = 0
    for num in lst:
        total += num
    result = total / len(lst)
    return result

lst = [1, 2, 3, 4, 5]

%timeit unknown_signature(lst)

287 ns ± 52.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [60]:
%timeit np.mean(lst)

7.41 μs ± 213 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [64]:
# Python code
def unknown_signature(lst, mask, new_value):
    for i in range(len(lst)):
        if mask[i]:
            lst[i] = new_value

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
unknown_signature(lst, mask, new_value)
lst

[0, 2, 0, 4, 0]

In [67]:
def numpy_unknown_signature(lst, mask, new_value):
    lst = np.array(lst)
    mask = np.array(mask)
    lst[mask] = new_value
    return lst
numpy_unknown_signature(lst, mask, new_value)

array([0, 2, 0, 4, 0])

### Task 7.2

In [69]:
# Python code
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

In [70]:
def numpy_unknown_signature(lst1, lst2):
    lst1 = np.array(lst1)
    lst2 = np.array(lst2)
    bitwise_complement = np.bitwise_not(lst1)
    bitwise_and = np.bitwise_and(lst1, lst2)
    bitwise_or = np.bitwise_or(lst1, lst2)
    return bitwise_complement, bitwise_and, bitwise_or
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

### Task 7.3 Optional

In [71]:
# Python code
def unknown_signature(lst):
    result = []
    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)
    return result

my_list = [6, 9, 12, 14, 17, 20]
result_python_style = unknown_signature(my_list)
result_python_style

[3, 13, 11, 21]

In [72]:
def numpy_unknown_signature(lst):
    lst = np.array(lst)
    mask = (lst % 2 == 0) & ((lst % 3 == 0) | (lst > 10))
    modified_lst = (np.bitwise_xor(lst[mask], 7)) + 2
    return modified_lst
numpy_unknown_signature(my_list)

array([ 3, 13, 11, 21])